feat: support to open the specify page in mpa mode
alibaba/ice pull request #3513
Opened 2020-09-08 15:09 UTC by chenbin92

## 功能说明

MPA 模式下支持打开特定的 URL 页面 https://github.com/alibaba/ice/issues/3511

### 默认启动页

在 MPA 模式下默认启动 pages 下的第一个页面作为启动页

```diff
"scripts": {
+   "start": "icejs start",
    "build": "icejs build"
  },
```

![image](https://user-images.githubusercontent.com/3995814/92494144-eb16ae80-f227-11ea-9af8-4ca94917d81a.png)

### 指定 `--map-entry`

```diff
"scripts": {
-   "start": "icejs start",
+   "start": "icejs start --mpa-entry Home",
    "build": "icejs build"
  },
```

![image](https://user-images.githubusercontent.com/3995814/92494410-43e64700-f228-11ea-9033-ccbf927e8ff9.png)

2020-09-10 04:23 UTC, ClarkXia requested changes

2020-09-10 04:23 UTC, ClarkXia commented on packages/plugin-react-app/src/index.js
> +      const srcDir = applyMethod('getSourceDir', entry);
需要处理下兼容

2020-09-10 07:31 UTC, chenbin92 commented on packages/plugin-react-app/src/index.js
> +      const srcDir = applyMethod('getSourceDir', entry);
更新了

2020-09-11 06:50 UTC, ClarkXia approved these changes

2020-09-14 01:38 UTC, merged