feat: support px2vw
alibaba/ice pull request #3546
Opened 2020-09-16 02:01 UTC by Yurisa

支持build-plugin-fusion px2vw能力，使用参数usePx2Vw进行控制，默认false不开启

2020-09-16 02:02 UTC, chenbin92 commented
@Yurisa 在 plugin-fusion 插件部分补充下使用文档。

2020-09-16 02:16 UTC, ClarkXia requested changes

2020-09-16 02:16 UTC, ClarkXia commented on packages/plugin-fusion/src/index.js
> +          .loader(require.resolve('postcss-loader'))
scss 和 scss-module 规则中默认已经有了 postcss-loader 的规则，可以通过修改 option 的方式即可

2020-09-16 02:17 UTC, Yurisa commented on packages/plugin-fusion/src/index.js
> +          .loader(require.resolve('postcss-loader'))
好👌 我看看

2020-09-17 08:03 UTC, ClarkXia approved these changes

2020-09-17 08:03 UTC, merged