Feat/support set html in mpa mode
alibaba/ice pull request #3566
Opened 2020-09-21 12:36 UTC by chenbin92

## 功能

- MPA 模式下支持指定 HTML 模板
- MPA 模式下支持指定打开页面

```json
"mpa": {
    "openPage": "Home",
    "template": {
      "web.html": ["Dashboard", "Home"]
    }
  },
```

2020-09-27 02:33 UTC, ClarkXia requested changes

2020-09-27 02:33 UTC, ClarkXia commented on packages/plugin-mpa/src/index.ts
> +      const htmlPluginOption = {
这块逻辑跟原先注册配置一致，不需要重复定义

2020-09-28 04:09 UTC, chenbin92 commented on packages/plugin-mpa/src/index.ts
> +      const htmlPluginOption = {
fixed

2020-09-28 04:28 UTC, ClarkXia approved these changes

2020-09-28 04:28 UTC, merged