feat: auto buildin icestore
alibaba/ice pull request #3932
Opened 2020-12-16 03:49 UTC by luhc228

Ref: https://github.com/raxjs/rax-app/issues/510

2020-12-17 12:06 UTC, ClarkXia requested changes

2020-12-17 12:06 UTC, ClarkXia commented on packages/plugin-app-core/src/index.ts
> +      plugins,
明确下 `defaultData` 的作用，这个数据最终是被 ejs 模版消费的。类似 plugin 和 dbugRuntime 的配置实际是并不需要渲染到页面上

2020-12-17 12:06 UTC, ClarkXia commented on packages/plugin-store/src/checkStoreAndModelExists.ts
> +
多余空格？ 可以看下 lint 规则是不是需要补充下

2020-12-17 12:06 UTC, ClarkXia commented on packages/plugin-store/src/checkStoreAndModelExists.ts
> +}
generator 也有 model / store 文件的拼装逻辑，尽量在一个地方维护

2020-12-18 09:09 UTC, luhc228 commented on packages/plugin-app-core/src/index.ts
> +      plugins,
fixed

2020-12-18 09:09 UTC, luhc228 commented on packages/plugin-store/src/checkStoreAndModelExists.ts
> +
fixed

2020-12-18 09:09 UTC, luhc228 commented on packages/plugin-store/src/checkStoreAndModelExists.ts
> +}
done

2020-12-20 07:00 UTC, SoloJiang commented on packages/plugin-app-core/src/generator/index.ts
>      }, this.parseRenderData());
这里的赋值逻辑没有问题吗

2020-12-20 07:04 UTC, SoloJiang commented on packages/plugin-store/src/index.ts
> +  const { mpa: isMpa, entry } = userConfig;
Rax 和 ICE MPA 判断逻辑不一样，获取多页信息的来源也不一样，Rax 不是扫目录拿到的入口信息

2020-12-20 07:06 UTC, SoloJiang commented on packages/plugin-store/src/utils/generatePath.ts
> +export function generateAppStorePath(rootDir: string, srcDir: string, projectType: string) {
这下面的命名有问题，本质上没有 generate 这个行为

2020-12-22 06:14 UTC, luhc228 commented on packages/plugin-app-core/src/generator/index.ts
>      }, this.parseRenderData());
fixed

2020-12-22 06:15 UTC, luhc228 commented on packages/plugin-store/src/index.ts
> +  const { mpa: isMpa, entry } = userConfig;
已作区分

2020-12-22 06:15 UTC, luhc228 commented on packages/plugin-store/src/utils/generatePath.ts
> +export function generateAppStorePath(rootDir: string, srcDir: string, projectType: string) {
fixed

2020-12-22 06:20 UTC, ClarkXia commented on packages/plugin-app-core/src/generator/index.ts
> +  public getDisableRuntimePlugins(): string[] {
这个 API 什么场景用到

2020-12-22 06:52 UTC, luhc228 commented on packages/plugin-app-core/src/generator/index.ts
> +  public getDisableRuntimePlugins(): string[] {
已去掉

2020-12-22 06:57 UTC, ClarkXia approved these changes

2020-12-22 07:03 UTC, SoloJiang approved these changes

2020-12-22 07:04 UTC, ClarkXia approved these changes

2020-12-22 07:32 UTC, merged