Feat: support dynamic tdk
alibaba/ice pull request #3937
Opened 2020-12-18 04:42 UTC by luhc228

Ref: #3901

2020-12-18 04:57 UTC, imsobear commented on packages/plugin-router/src/runtime/formatRoutes.tsx
> +            modifyPageTDK(pageTDKData);
CSR 的场景不需要支持 __SSR_PAGE_TDK__ 吧？

2020-12-18 04:57 UTC, imsobear commented on packages/plugin-router/src/runtime/formatRoutes.tsx
> +            modifyPageTDK(pageTDKData);
假设直接访问的是 home 页面，SSR 输出了 TDK，这时候前端路由切换到 about 页面，我认为  TDK 可以不用变化。

2020-12-18 07:08 UTC, luhc228 commented on packages/plugin-router/src/runtime/formatRoutes.tsx
> +            modifyPageTDK(pageTDKData);
fixed.
补充最后的结论：暂时的方案是，如果在 CSR 下，切换路由后，需要更新页面的 title，可以使用 pageConfig.title

2020-12-18 08:11 UTC, imsobear commented on packages/plugin-ice-ssr/src/server.ts.ejs
> +    if (pageInitialProps && pageInitialProps.__SSR_PAGE_TDK__) {
这里好像可以顺便把 pageConfig.title 支持掉

2020-12-21 07:42 UTC, ClarkXia commented
能在一个地方配置 不管 CSR 还是 SSR 都生效吗

2020-12-22 02:54 UTC, ClarkXia requested changes

2020-12-22 02:54 UTC, ClarkXia commented on packages/plugin-ice-ssr/src/server.ts.ejs
> +    $('head').append(`${helmet.meta.toString()}`)
考虑全面点 比如 link 和 script 是不是也需要

2020-12-22 03:23 UTC, luhc228 commented on packages/plugin-ice-ssr/src/server.ts.ejs
> +    $('head').append(`${helmet.meta.toString()}`)
fixed

2020-12-22 06:55 UTC, ClarkXia approved these changes

2020-12-22 07:03 UTC, ClarkXia requested changes

2020-12-22 07:03 UTC, ClarkXia commented on packages/plugin-ice-ssr/src/index.ts
> +  applyMethod('addExport', { source: 'react-helmet', specifier: '{ Helmet }', exportName: 'Helmet' });
在 ssr 插件中使用 不开启 ssr 的时候 Helmet 不能使用了

2020-12-22 07:30 UTC, luhc228 commented on packages/plugin-ice-ssr/src/index.ts
> +  applyMethod('addExport', { source: 'react-helmet', specifier: '{ Helmet }', exportName: 'Helmet' });
fixed

2020-12-22 07:33 UTC, ClarkXia requested changes

2020-12-22 07:33 UTC, ClarkXia commented on packages/plugin-ice-ssr/package.json
> +    "react-helmet": "^6.1.0"
依赖移除

2020-12-22 07:36 UTC, luhc228 commented on packages/plugin-ice-ssr/package.json
> +    "react-helmet": "^6.1.0"
已移除

2020-12-22 07:41 UTC, ClarkXia requested changes

2020-12-22 07:41 UTC, ClarkXia commented on packages/plugin-helmet/tsconfig.json
> +  },
不标准的 json

2020-12-22 07:43 UTC, ClarkXia approved these changes

2020-12-22 07:44 UTC, luhc228 commented on packages/plugin-helmet/tsconfig.json
> +  },
fixed

2020-12-22 07:48 UTC, merged