Fix/more import specifier
alibaba/ice pull request #4008
Opened 2021-01-11 03:10 UTC by maoxiaoke

Close #4007

2021-01-11 03:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/ice?pullRequest=4008) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/ice?pullRequest=4008) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/ice?pullRequest=4008) it.</sub>

2021-01-11 04:17 UTC, ClarkXia requested changes

2021-01-11 04:17 UTC, ClarkXia commented on packages/plugin-icestark/src/runtime.tsx
> +          const mountNode = getMountNode();
这里需要考虑 cache 场景，必须动态获取

2021-01-12 02:40 UTC, maoxiaoke commented on packages/plugin-icestark/src/runtime.tsx
> +          const mountNode = getMountNode();
代码已移除

2021-01-12 13:55 UTC, ClarkXia approved these changes

2021-01-13 08:55 UTC, merged