use <Head> replace <Helmet>
alibaba/ice pull request #4069
Opened 2021-01-28 06:08 UTC by luhc228

2021-02-02 06:09 UTC, ClarkXia commented on packages/plugin-helmet/src/index.ts
> +    exportDefault: 'Head'
exportMembers 用于分包逻辑，改成 exportDefault 意味这个最终转化为 import Head from 'react-helmet';

2021-02-04 08:56 UTC, luhc228 commented on packages/plugin-helmet/src/index.ts
> +    exportDefault: 'Head'
fixed

2021-02-05 02:59 UTC, ClarkXia requested changes

2021-02-05 02:59 UTC, ClarkXia commented on packages/plugin-helmet/src/index.ts
> +    exportName: `
import { Head } from 'ice'; 这个逻辑要最终转化为 import { Helmet } from 'react-helmet'; 目前的转化是做不到的，需要增加类似 alias 的映射关系

2021-02-05 02:59 UTC, ClarkXia commented on packages/plugin-helmet/src/index.ts
>      exportMembers: ['Helmet'],
exportMembers 是用来判断哪些是需要被转化的，现在 Head 没见加进来

2021-02-22 06:30 UTC, luhc228 commented on packages/plugin-helmet/src/index.ts
> +    exportName: `
我增加了 alias 字段以作为映射关系

2021-02-22 06:31 UTC, luhc228 commented on packages/plugin-helmet/src/index.ts
>      exportMembers: ['Helmet'],
已增加

2021-02-22 06:38 UTC, luhc228 commented on packages/plugin-helmet/src/index.ts
> +    exportName: `
另外，原有的逻辑遇到下面的情况，转换以后是有问题的：
```js
// 转换前
import {  store as appStore } from 'ice';
// 转换后
import store from 'ice/store/index';

// 用户使用时，没有 appStore
appStore.useStore('counter');
```
在这里顺带修复了这个问题

2021-02-22 06:51 UTC, ClarkXia approved these changes

2021-02-22 06:54 UTC, ClarkXia commented on packages/plugin-app-core/src/config/setRegisterMethod.ts
> +      importDeclarationsAlias[key] = alias[key];
importDeclarationsAlias 是不是直接可以在 importDeclarations 里承载掉，这样不用再增加一个参数

2021-02-22 08:19 UTC, luhc228 commented on packages/plugin-app-core/src/config/setRegisterMethod.ts
> +      importDeclarationsAlias[key] = alias[key];
done

2021-02-22 10:06 UTC, ClarkXia approved these changes

2021-02-23 06:09 UTC, SoloJiang approved these changes

2021-02-23 06:10 UTC, merged