fix: 🐛 make router.basename work in icestark context
alibaba/ice pull request #4243
Opened 2021-04-16 02:35 UTC by maoxiaoke

Closes #4234

2021-04-16 02:43 UTC, ClarkXia requested changes

2021-04-16 02:43 UTC, ClarkXia commented on packages/plugin-icestark/src/runtime.tsx
> +    const childBasename = isInIcestark ? getBasename() : basename;
isInIcestark 是个 function

2021-04-20 07:44 UTC, ClarkXia approved these changes

2021-04-20 11:54 UTC, luhc228 approved these changes

2021-04-21 02:16 UTC, merged