[WIP] Feat/multi theme
alibaba/ice pull request #4349
Opened 2021-05-31 02:43 UTC by FuzzyFade

## TODO
- [x] 基本能力
- [ ] 修复 PostCss 相关 Bug
- [ ] Less/Sass 函数预编译
- [ ] 主题数据懒加载

[通用多主题相关 RFC](https://github.com/alibaba/ice/issues/4223)

2021-07-05 06:36 UTC, ClarkXia commented on packages/plugin-theme/src/utils/injectThemes.ts
> +      config.entry(name).prepend(jsPath);
DefineVariablePlugin 的逻辑可以统一添加到 jsPath 中吧

2021-07-05 06:36 UTC, ClarkXia commented on examples/with-multi-themes/build.json
> +        "themePackage": "@alifd/theme-design-pro"
在 fusion 的主题场景下 应该建议在 themes/dark.css 中引入主题

2021-07-05 06:36 UTC, ClarkXia commented on examples/with-multi-themes/src/themes/dark.css
> +:root {
还需要一个基于 antd 的多主题应该怎么写，比如 antd 的组件默认提供了 dark / light 的内置主题，怎么快速引入到主题方案中

2021-07-05 07:47 UTC, FuzzyFade commented on packages/plugin-theme/package.json
> +    "@alib/build-scripts": "^0.1.20",
我这里直接用 `npm init ice <your-plugin-name>` 生成的插件模板...

2021-07-05 07:53 UTC, FuzzyFade commented on packages/plugin-theme/src/plugins/webpack/DefineVariablePlugin.ts
> +export type VarTarget = 'const' | 'window' | 'global';
本来想设置多个类型的变量注入...然后作为可选项在插件的 option 透出，现在感觉没啥必要考虑这方面的通用性了，应该可以删了

2021-07-05 09:25 UTC, imsobear requested changes

2021-07-05 09:25 UTC, imsobear commented on packages/plugin-theme/src/utils/common.ts
> +export const getDefaultThemes = (names: string[]) => {
getDefaultTheme

2021-07-05 09:25 UTC, imsobear commented on packages/plugin-theme/src/index.ts
> +    log.info(`🤔 未找到默认主题文件（default），自动配置 ${defaultName} 为初始主题`);
default.css

2021-07-05 09:25 UTC, imsobear commented on packages/plugin-theme/template/injectTheme.js.ejs
> +window.__handleTheme__ = handleTheme;
这个我感觉跟着 utils/injectTheme 更合理点

2021-07-05 09:25 UTC, imsobear commented on packages/plugin-theme/src/index.ts
> +  setVariable(onGetWebpackConfig, defaultName);
这个三个 API 的命名最好能再具体点

2021-07-05 09:25 UTC, imsobear commented on packages/plugin-theme/src/utils/injectThemes.ts
> +      config.entry(name).prepend(jsPath);
同意，注入运行时代码最好放在一起，方便观察关联性。另外 utils 下不要太过扁平，可以按照功能纬度聚合下

2021-07-05 09:35 UTC, FuzzyFade commented on packages/plugin-theme/template/injectTheme.js.ejs
> +window.__handleTheme__ = handleTheme;
injectTheme 是注入数据，而 handleTheme 是注入逻辑。

2021-07-05 09:36 UTC, FuzzyFade commented on packages/plugin-theme/src/utils/common.ts
> +export const getDefaultThemes = (names: string[]) => {
done

2021-07-05 09:36 UTC, FuzzyFade commented on packages/plugin-theme/src/index.ts
> +    log.info(`🤔 未找到默认主题文件（default），自动配置 ${defaultName} 为初始主题`);
done

2021-07-05 09:36 UTC, FuzzyFade commented on packages/plugin-theme/src/index.ts
> +    log.info('🤔 未找到主题文件，不开启多主题适配');
done

2021-07-05 09:36 UTC, FuzzyFade commented on packages/plugin-theme/src/index.ts
> +  const enableThemes = await getEnableThemes(themesPath);
done

2021-07-05 09:36 UTC, FuzzyFade commented on packages/plugin-theme/src/utils/common.ts
> +export const getEnableThemes = async (themesPath: string): Promise<boolean> => {
done

2021-07-05 09:52 UTC, FuzzyFade commented on packages/plugin-theme/src/plugins/webpack/DefineVariablePlugin.ts
> +export type VarTarget = 'const' | 'window' | 'global';
done

2021-07-05 09:53 UTC, FuzzyFade commented on packages/plugin-theme/package.json
> +    "@alib/build-scripts": "^0.1.20",
done

2021-07-05 10:20 UTC, FuzzyFade commented on packages/plugin-theme/src/utils/injectThemes.ts
> +      config.entry(name).prepend(jsPath);
done

2021-07-05 10:20 UTC, FuzzyFade commented on packages/plugin-theme/src/plugins/webpack/DefineVariablePlugin.ts
> +            if (fileName.includes('index')) {
done

2021-07-05 10:21 UTC, FuzzyFade commented on packages/plugin-theme/src/index.ts
> +  setVariable(onGetWebpackConfig, defaultName);
done

2021-07-07 08:02 UTC, FuzzyFade commented on packages/plugin-theme/src/utils/common.ts
> +  return filePath.replace(/(.*\/)*([^.]+).*/ig, '$2');
fixed

2021-07-07 09:49 UTC, FuzzyFade commented on examples/with-multi-themes/src/themes/dark.css
> +:root {
P1

2021-07-08 05:51 UTC, imsobear commented on examples/with-multi-themes/build.json
> +        "themePackage": "@alifd/theme-design-pro"
这个应该去除吧？

2021-07-08 05:51 UTC, imsobear commented on examples/with-multi-themes/src/themes/default.css
> +}
示例加下 fusion 组件的、default.css -> light.css

2021-07-08 05:51 UTC, imsobear commented on examples/with-multi-themes/src/test.css
> +}
这个文件的最用是？

2021-07-08 05:51 UTC, imsobear commented on packages/plugin-theme/package.json
> +  },
全都是 dev 依赖吗？

2021-07-08 06:18 UTC, FuzzyFade commented on examples/with-multi-themes/src/test.css
> +}
测试 import

2021-07-08 06:39 UTC, FuzzyFade commented on packages/plugin-theme/package.json
> +  },
fixed

2021-07-08 07:34 UTC, ClarkXia commented on packages/plugin-store/src/pageSourceLoader.ts
> +        pageSource: join(String(targetPath), pageSource)
为啥改到了这里 是类型问题？

2021-07-08 07:34 UTC, ClarkXia commented on packages/plugin-theme/src/plugins/webpack/DefineVariablePlugin.ts
> +        (assets) => {
assets 应该是所有的资源输出，包括按需加载的分包，可以结合 compiler 上的 entry 处理。这个逻辑可以再确认下

2021-07-08 07:34 UTC, ClarkXia commented on packages/plugin-theme/src/index.ts
> +  const _theme = get(<Options>options, 'theme', 'default');
`_theme` 有下划线命名的原因是什么

2021-07-08 07:34 UTC, ClarkXia commented on packages/plugin-theme/src/workflow/injectVariable.ts
> +        .use('postcss-loader')
默认链路也内置了 postcss-loader，是不是只要合并 loader 的 options 就行

2021-07-08 07:35 UTC, FuzzyFade commented on packages/plugin-theme/src/index.ts
> +  const _theme = get(<Options>options, 'theme', 'default');
因为已经有 defaultName 了

2021-07-08 07:36 UTC, FuzzyFade commented on packages/plugin-store/src/pageSourceLoader.ts
> +        pageSource: join(String(targetPath), pageSource)
之前就有这个类型问题

2021-07-08 07:39 UTC, FuzzyFade commented on packages/plugin-theme/src/workflow/injectVariable.ts
> +        .use('postcss-loader')
好像不行

2021-07-08 07:40 UTC, FuzzyFade commented on packages/plugin-theme/src/workflow/injectVariable.ts
> +        .use('postcss-loader')
因为加了 parser，但之前链路上的那个 postcss-loader 的版本不支持这个 option

2021-07-08 08:42 UTC, ClarkXia commented on packages/plugin-theme/src/workflow/injectVariable.ts
> +        .use('postcss-loader')
看下需要哪个版本 可以升级上去

2021-07-13 09:53 UTC, ClarkXia commented on packages/plugin-theme/src/plugins/helper/resolver.ts
> +  return resolveModule(`./${id}`, resolveOpts)
这个 id 统一拼接相对路径的原因是什么
另外类似 sass 的 `@import` 需要确认下多方式 import 场景下的表现，比如：
```css
@import "theme.css";
@import "http://fonts.googleapis.com/css?family=Droid+Sans";
@import url(theme);
@import "landscape" screen and (orientation: landscape);
```

2021-07-14 03:15 UTC, FuzzyFade commented on packages/plugin-theme/src/plugins/helper/resolver.ts
> +  return resolveModule(`./${id}`, resolveOpts)
这行代码有一层 try catch：优先匹配相对路径，如果该路径上的文件不存在则匹配模块路径。
其他的 import 情况会直接交给 sass-loader/less-loader 来管理。

2021-07-14 03:15 UTC, FuzzyFade commented on packages/plugin-theme/src/plugins/helper/resolver.ts
> +  return resolveModule(`./${id}`, resolveOpts)
done

2021-07-14 03:28 UTC, ClarkXia commented on packages/plugin-theme/src/plugins/helper/walkers.ts
> +  const blacklist = ['/reset', '_shadow', '_mixin', '_function'];      // 扫描文件的黑名单
现在是直接忽略这个几个文件处理，这种方式给主题方案带来的影响是什么？antd 的引入文件名应该不一样吧

2021-07-14 03:43 UTC, FuzzyFade commented on packages/plugin-theme/src/plugins/helper/walkers.ts
> +  const blacklist = ['/reset', '_shadow', '_mixin', '_function'];      // 扫描文件的黑名单
这部分是调试代码，还没删掉。
正式的话会使用这种方式：['/reset', 'mixin', '_']
主要目的是 fusion 和 antd 里的 mixin 文件会让扫描逻辑爆栈，而且它们是否参与扫描对结果的影响不大。

2021-07-14 06:14 UTC, ClarkXia commented on packages/plugin-theme/src/plugins/helper/walkers.ts
> +  const blacklist = ['/reset', '_shadow', '_mixin', '_function'];      // 扫描文件的黑名单
内存溢出的原因是什么

2021-07-14 06:16 UTC, ClarkXia commented
文件冲突合并下

2021-07-14 07:36 UTC, ClarkXia approved these changes

2021-07-14 07:37 UTC, FuzzyFade commented on packages/plugin-theme/src/plugins/helper/walkers.ts
> +  const blacklist = ['/reset', '_shadow', '_mixin', '_function'];      // 扫描文件的黑名单
这里先 mark 一下

2021-07-14 08:22 UTC, imsobear approved these changes

2021-07-14 08:24 UTC, merged