Feat/omit set library name
alibaba/ice pull request #4371
Opened 2021-06-07 09:58 UTC by maoxiaoke

- [x] get rendering container through `props` instead of `getMountNode`. ([#227](https://github.com/ice-lab/icestark/issues/227))
- [x] support `omitSetLibraryName` for removing default setLibraryName.

2021-06-09 11:33 UTC, ClarkXia requested changes

2021-06-09 11:33 UTC, ClarkXia commented on packages/plugin-icestark/src/types/index.ts
> +  [k: string]: any;
这个类型的原因

2021-06-09 11:33 UTC, ClarkXia commented on packages/plugin-icestark/src/runtime.tsx
> +            const { container, customProps = {} } = $$props ?? {};
在 1.x 的框架应用下 container 不存在的情况

2021-06-09 11:33 UTC, ClarkXia commented on packages/plugin-icestark/src/runtime.tsx
> +            ReactDOM.render(<App {...customProps} />, container, resolve);
如何消费这个 customProps

2021-06-09 11:33 UTC, ClarkXia commented on packages/plugin-icestark/package.json
> +    "@ice/stark-data": "^0.1.2",
无用依赖

2021-06-15 06:23 UTC, maoxiaoke commented on packages/plugin-icestark/package.json
> +    "@ice/stark-data": "^0.1.2",
done

2021-06-15 08:25 UTC, maoxiaoke commented on packages/plugin-icestark/src/runtime.tsx
> +            ReactDOM.render(<App {...customProps} />, container, resolve);
done

2021-06-15 08:30 UTC, maoxiaoke commented on packages/plugin-icestark/src/runtime.tsx
> +            ReactDOM.render(<App {...customProps} />, container, resolve);
通过 PageComponent 的 props 来消费

2021-06-15 12:41 UTC, ClarkXia commented on packages/plugin-icestark/src/types/index.ts
> +  $$props: {
这个类型应该会暴露在 IAppConfig 上，尽量通过 extend 等方式单独进行定义

2021-06-16 04:09 UTC, maoxiaoke commented on packages/plugin-icestark/src/types/index.ts
> +  $$props: {
done

2021-06-16 09:49 UTC, ClarkXia commented on packages/plugin-icestark/src/runtime.tsx
> +import { InnerIceStark, IIceStark } from './types';
InnerIceStark？  规范上默认以 I 开头后面跟具体的命名

2021-06-16 11:04 UTC, maoxiaoke commented on packages/plugin-icestark/src/runtime.tsx
> +import { InnerIceStark, IIceStark } from './types';
done

2021-06-17 03:00 UTC, ClarkXia commented on packages/plugin-icestark/src/runtime.tsx
> +        ...customProps,
props 上可能会有什么属性，如果直接解构 customProps 覆盖的几率是不是比较高

2021-06-17 03:05 UTC, maoxiaoke commented on packages/plugin-icestark/src/runtime.tsx
> +        ...customProps,
均收敛到 frameworkProps 字段中

2021-06-17 08:31 UTC, ClarkXia approved these changes

2021-06-17 08:41 UTC, SoloJiang approved these changes

2021-06-17 09:38 UTC, merged