feat: module federation for development
alibaba/ice pull request #4382
Opened 2021-06-11 06:43 UTC by ClarkXia

2021-07-05 07:43 UTC, FuzzyFade requested changes

2021-07-05 07:43 UTC, FuzzyFade commented on packages/plugin-react-app/src/userConfig/remoteRuntime/writeRemoteFile.ts
> +  }).filter(Boolean);
建议直接用 `reduce` 写
```typescript
runtimeContents.reduce((acc, { packageName, exposeContent }) => {
  if (exposeContent) {
    const exposePath = path.join(exposesTemp, packageName);
    const tempDir = path.join(rootDir, exposePath);
    fse.ensureDirSync(tempDir);
    fse.writeFileSync(path.join(tempDir, 'index.js'), exposeContent);
    acc.push({ packageName, exposePath })
  }
  return acc
}, [])
```

2021-07-05 07:43 UTC, FuzzyFade commented on packages/plugin-react-app/src/userConfig/remoteRuntime/preBuild.ts
> +  [key: string]: string;
建议直接用 `Record<string, string>`

2021-07-05 07:43 UTC, FuzzyFade commented on packages/plugin-react-app/src/userConfig/remoteRuntime/getCompileDeps.ts
> +      || excludePackages.some(str => packageName === str)) {
instead of `includes`

2021-07-05 07:43 UTC, FuzzyFade commented on packages/plugin-react-app/src/userConfig/remoteRuntime/getCacheContent.ts
> +  }).filter(Boolean);
这里也可以改成写 `reduce`

2021-07-05 07:43 UTC, FuzzyFade commented on packages/plugin-react-app/src/userConfig/remoteRuntime/getCompileDeps.ts
> +}
这里为啥不直接用 type 写成一行？如果用 interface 的话在理解的时候可能会和下面这个逻辑弄混

````typescript
interface ICheckFunction {
  [packageName: string]: boolean;
}
```

2021-07-05 07:43 UTC, FuzzyFade commented on packages/plugin-react-app/package.json
> +    "webpack": "^4.41.1",
这里的版本号确定没问题吗

2021-07-05 09:03 UTC, FuzzyFade reviewed
https://github.com/alibaba/ice/pull/4382/files/09d34d24721b563e396d055bd699cf48a326445c#diff-124b985354321150eae26be337b0df2324520564d8bffaf6901dc9a0344fe0daR5
这里引的 mini app 相关的 api 需要删掉吗

2021-07-05 09:25 UTC, ClarkXia commented
> https://github.com/alibaba/ice/pull/4382/files/09d34d24721b563e396d055bd699cf48a326445c#diff-124b985354321150eae26be337b0df2324520564d8bffaf6901dc9a0344fe0daR5
> 这里引的 mini app 相关的 api 需要删掉吗

已删除

2021-07-05 09:25 UTC, ClarkXia commented on packages/plugin-react-app/package.json
> +    "webpack": "^4.41.1",
dev 依赖 已升级成 5

2021-07-05 09:25 UTC, ClarkXia commented on packages/plugin-react-app/src/userConfig/remoteRuntime/getCompileDeps.ts
> +}
done

2021-07-05 09:25 UTC, ClarkXia commented on packages/plugin-react-app/src/userConfig/remoteRuntime/getCacheContent.ts
> +  }).filter(Boolean);
done

2021-07-05 09:26 UTC, ClarkXia commented on packages/plugin-react-app/src/userConfig/remoteRuntime/getCompileDeps.ts
> +      || excludePackages.some(str => packageName === str)) {
excludePackages 是严格匹配的包，跟 includesStrings 逻辑有点不一样

2021-07-05 09:26 UTC, ClarkXia commented on packages/plugin-react-app/src/userConfig/remoteRuntime/preBuild.ts
> +  [key: string]: string;
done

2021-07-05 09:26 UTC, ClarkXia commented on packages/plugin-react-app/src/userConfig/remoteRuntime/writeRemoteFile.ts
> +  }).filter(Boolean);
done

2021-07-05 09:31 UTC, FuzzyFade commented on packages/plugin-react-app/src/userConfig/remoteRuntime/getCompileDeps.ts
> +      || excludePackages.some(str => packageName === str)) {
这里应该是 some -> includes

2021-07-05 09:37 UTC, ClarkXia commented on packages/plugin-react-app/src/userConfig/remoteRuntime/getCompileDeps.ts
> +      || excludePackages.some(str => packageName === str)) {
done

2021-07-05 09:57 UTC, FuzzyFade approved these changes

2021-07-07 03:59 UTC, SoloJiang commented on packages/plugin-react-app/src/userConfig/remoteRuntime/babelPluginRemote.ts
> +    if (node.source && isMatchRemote(node.source.value, libs) && process.env.RRE_BUILD !== 'true') {
前面判断过 node.source 了

2021-07-07 06:55 UTC, ClarkXia commented on packages/plugin-react-app/src/userConfig/remoteRuntime/babelPluginRemote.ts
> +    if (node.source && isMatchRemote(node.source.value, libs) && process.env.RRE_BUILD !== 'true') {
fixed

2021-07-07 09:17 UTC, SoloJiang approved these changes

2021-07-07 13:23 UTC, merged