chore: optimize file path
alibaba/ice pull request #4499
Opened 2021-07-26 09:16 UTC by SoloJiang

`.ice` 目录下均生成相对路径，而不是复杂的绝对路径

2021-07-26 09:23 UTC, ClarkXia requested changes

2021-07-26 09:23 UTC, ClarkXia commented on packages/build-mpa-config/src/generate/BaseGenerator.ts
> +      relativeCorePath: path.relative(this.entryFolder, path.join(this.targetDir, 'core')),
path.relative 兼容下 win，format 下

2021-07-26 12:27 UTC, SoloJiang commented on packages/build-mpa-config/src/generate/BaseGenerator.ts
> +      relativeCorePath: path.relative(this.entryFolder, path.join(this.targetDir, 'core')),
done

2021-07-27 03:20 UTC, ClarkXia approved these changes

2021-07-27 03:20 UTC, merged