fix: postcss plugin resolve
alibaba/ice pull request #4967
Opened 2021-11-24 13:23 UTC by wjq990112

- fix: history referenced by GID is undefined (#4290)
- feat: upgrade packages for webpack 5 (#4245)
- fix: add nodejieba
- chore: bump dependency version (#4336)
- fix: postcss version
- feat: built-in react fast refresh (#4340)
- feat: runtime structure refactor (#4346)
- feat: remove deprecated configs (#4359)
- feat: improve router configuration (#4364)
- feat: refactor runtime module of create-app-share (#4429)
- fix: format runtime folder (#4438)
- feat: module federation for development (#4382)
- feat: support publish with dist-tag (#4437)
- fix: upgrade dependencies pack (#4442)
- refactor: build-plugin-ice-auth remove @ice/store (#4453)
- feat: support swc (#4178)
- chore: deprecate packages and api (#4452)
- feat: upgrade @ice/store (#4451)
- fix: set alias for webpack/hot (#4457)
- chore: tag next version and changelog (#4447)
- chore: bump @builder/pack version (#4466)
- feat: multi theme (#4349)
- fix: await runtime generation (#4467)
- refactor: mpa render (#4468)
- feat: support webpack-dev-server v4 (#4478)
- fix: import declartions and devServer (#4489)
- chore: optimize file path (#4499)
- feat: enhance debug package (#4505)
- fix: compatible with plugins when swc is enabled (#4506)
- feat: vite mode of icejs (#4481)
- chore: version
- chore: update lock file
- fix: redirection of runApp in mode MPA (#4507)
- refactor: rework logger plugin (#4497)
- feat: support pre compile by swc (#4509)
- fix: build error in vite mode (#4511)
- chore: package.json files
- fix: special treatment for package.json resolution with exports (#4508)
- fix: update pre compiled dependencies (#4522)
- feat: support specify minifier by config minify (#4523)
- refactor: replace route path in plugin-store (#4501)
- fix: reset pre-bundling entry (index.html -> js entry) (#4524)
- chore: remove useless dependency
- feat: transform some ice config to vite config (#4519)
- fix: plugin-auth type warning (#4529)
- feat: support style import in vite (#4528)
- feat: vite plugin for import component style (#4527)
- fix: oom when use filesystem cache (#4531)
- fix: hmr when development (#4532)
- fix: polyfill file in hash and outputAssetsPath (#4533)
- fix: config webpack runtime target (#4540)
- fix: analyze runtime before generate (#4541)
- fix: compatible with swc enabled (#4537)
- fix: conditionNames for exports field (#4544)
- chore: dependencies (#4545)
- feat: vite MPA & performance (#4538)
- chore: update lock file
- fix: remove assets directory (#4548)
- fix: recompile when use store (#4551)
- Fix: react-refresh in vite mode (#4550)
- fix: vite alias config cover (#4555)
- Fix: pages/index.jsx has error when enable store (#4556)
- fix: compatible with runtime generation when react-jsx is enabled (#4557)
- chore: upgrade dependencies (#4559)
- fix: migrate webpack-dev-server to ^4.0.0 (#4560)
- fix: compatible with runtime generation when react-jsx is enabled (#4563)
- fix: compatible with win32 (#4562)
- fix: enable trusted cert of https in vite mode (#4565)
- fix: format match routes in win32 (#4568)
- feat: swc minify code (#4571)
- fix: compatible with runtime extensions (#4573)
- Feat: ssg (#4542)
- fix: preprocessorOptions transformer (#4567)
- chore: bump verison of build-scripts (#4575)
- fix: unable import svg and more files in webpack mode (#4576)
- fix: ignore html in mpa (#4582)
- feat: refactor config of minify (#4578)
- chore: verison
- feat: support fusion theme config in vite (#4588)
- fix: terser options transform (#4590)
- chore: remove useless plugin
- fix: rule test of redirect-path-loader (#4592)
- feat: support custom publish verison
- feat: mock for vite (#4595)
- fix: typo of vite define (#4598)
- fix: compatible with plugin-icestark (#4597)
- feat: support rax-app (#4546)
- fix: global polyfill (#4601)
- fix: get history (#4600)
- fix: config auth by static props of component (#4614)
- fix: proxy in vite mode (#4618)
- feat: generate 404.html (#4599)
- feat: pwa (#4490)
- chore: lock file
- feat: 🎸 support es module for ice.js (#4603)
- fix: runtime file generate by icestark (#4619)
- chore: remove deprecate type (#4625)
- feat: add strict mode to app config (#4514)
- chore: not generate server loadable stats file (#4626)
- fix: update auth (#4624)
- feat: validate vite config (#4623)
- fix: remove runtime config of logger (#4622)
- fix: windows build error in vite mode (#4627)
- feat: add immer usage example (#4633)
- fix: add dependency of react-router-dom to fix yarn install (#4631)
- feat: support publish stable (#4634)
- fix: publish scripts of get dist-tags (#4637)
- fix: compatible with different version of icejs (#4639)
- chore: update lock
- fix: order of core-js modules (#4632)
- chore: add dependency of react-router for yarn install
- feat: lock axios version (#4640)
- fix: runtime compile
- fix: test case
- fix: test case
- fix: test case for request
- fix: test case for icestark
- fix: builder blocked in windows (#4642)
- docs(README): update contributors
- feat: bundle swc (#4645)
- chore: version
- chore: generator to Generator
- Revert "chore: generator to Generator" (#4690)
- chore: version
- fix: display warning message but the page has no store (#4693)
- fix: set history value after initHistory (#4694)
- feat: moment locales in vite mode (#4685)
- fix: theme icon in vite mode (#4683)
- fix: jest config (#4695)
- chore: plugin-store version (#4699)
- fix: Component.getInitialProps function isn't be executed (#4682)
- chore: version
- Fix: redirectUrl is undefined (#4701)
- release/plugin-icestark-1-4-0 (#4678)
- feat(create-ice): add Ant Design scaffold (#4707)
- fix: compatible with webpack5 of webpack-plugin-import (#4710)
- fix: add dependency of eslint report plugin (#4712)
- fix: win32 path of theme icon in vite mode (#4715)
- fix: set history after createHistory (#4732)
- fix: 🐛 change loader options involved in object (#4718)
- release: plugin-stark-module@2.2.0 (#4635)
- Fix: swc error with build mode (#4728)
- feat: compat rax-app (#4609)
- chore: lint
- chore: remove getSearchParams in runtimeAPI for rax-app (#4738)
- fix: transform additionalData for pre-processor (#4736)
- fix: compat rax-app (#4739)
- feat: vite plugin of tsChecker (#4740)
- fix: prevent to read postcss config which unexpected (#4711)
- fix: resolve style by module (#4749)
- feat: add runtime plugin wrapper to miniapp (#4752)
- fix: add default ErrorBoundary for mpa (#4770)
- fix: refactor eslint config (#4751)
- feat: eslint plugin for vite mode (#4747)
- Fix: can run project normally when first use store (#4708)
- feat: support minify some tasks (#4764)
- release: plugin-stark-module@2.2.1
- chore: update dependencies of webpack-dev-mock (#4773)
- fix: update dependencies (#4771)
- fix: default value of eslint (#4778)
- chore: version and changelog (#4775)
- fix: es module
- fix: ts type error (#4781)
- fix: assets rule for static resource (#4782)
- fix: print urls after server created (#4785)
- fix: oom when use filesystem cache (#4791)
- feat: plugin for ignore style import (#4776)
- feat: support disableModularImport of build-plugin-antd (#4788)
- fix: rax app build error (#4790)
- fix: deprecate check of componentConfig when import style path (#4789)
- Fix: nested routes not render in vite (#4787)
- feat: global.styl can be auto loaded (#4692)
- feat: support to watch global.styl (#4801)
- fix: generate sourcemap with inject moment locales (#4795)
- feat: support disableModularImport for plugin-fusion (#4802)
- chore: version (#4812)
- fix: pre build moment locales (#4804)
- feat: tilde alias for component style (#4816)
- chore: verison
- Release: plugin-icestark 2.4.1 (#4817)
- fix(ci): use custom github token (#4714)
- docs(README): update contributors
- fix: transform postcssOptions for vite (#4835)
- chore: bump version of esbuild (#4846)
- fix: default style regexp of build-plugin-ignore-style (#4847)
- chore: update node engines (#4830)
- fix: error occured with config sourceMap (#4823)
- fix: typo of vitePlugins (#4851)
- fe [...]

2021-11-29 06:34 UTC, ClarkXia requested changes

2021-11-29 06:34 UTC, ClarkXia commented on packages/build-user-config/package.json
> +    "postcss-preset-env": "^6.7.0",
测试用的到包 不要放到 dependencies 中

2021-11-29 06:34 UTC, ClarkXia commented on packages/build-user-config/src/userConfig/postcssOptions.js
> +    delete postcssOptions.plugins;
postcssOptions 其他地方可能使用，不能直接删除引用

2021-11-29 06:34 UTC, ClarkXia commented on packages/build-user-config/src/userConfig/postcssOptions.js
> +      postcssOptions.postcssOptions = postcssOptions.postcssOptions || {};
同上，不要直接修改用户的配置

2021-12-01 09:59 UTC, ClarkXia approved these changes

2021-12-02 02:36 UTC, SoloJiang approved these changes

2021-12-02 02:37 UTC, merged