feat: optimize runtime when build
alibaba/ice pull request #5082
Opened 2021-12-28 12:09 UTC by ClarkXia

Resolve #5048

2022-01-04 07:04 UTC, imsobear requested changes

2022-01-04 07:04 UTC, imsobear commented on packages/build-app-helpers/src/analyzeRuntime.ts
> +      source = (await transform(source, { loader })).code;
这里不加下判断么？只有 ts 要转换？

2022-01-04 07:04 UTC, imsobear commented on packages/build-app-helpers/src/analyzeRuntime.ts
> +        await init;
这个用法好奇怪 =。=

2022-01-04 07:40 UTC, ClarkXia commented on packages/build-app-helpers/src/analyzeRuntime.ts
> +        await init;
init 主要用于 wasm 的加载，已修正

2022-01-04 07:41 UTC, ClarkXia commented on packages/build-app-helpers/src/analyzeRuntime.ts
> +      source = (await transform(source, { loader })).code;
fixed

2022-01-04 07:42 UTC, ClarkXia commented on packages/plugin-mpa/src/index.ts
> +          onHook('before.build.load', async (options) => {
MPA 的场景需要对多个入口分析，如果不是循环创建 onHook 也是，onHook 内部进行循环。本质上都会按顺序执行，逻辑上没有区别

2022-01-04 07:45 UTC, ClarkXia commented on packages/build-mpa-config/src/generate/index.ts
> +  // 需要在分析完成并执行 disableRuntimePlugins 逻辑后，再执行生成
因为 analyzeRuntime 依赖完整的 webpack 配置，所有分析的行为必须发生在 `before.${command}.load` 阶段

2022-01-04 07:45 UTC, ClarkXia commented on packages/plugin-mpa/src/index.ts
> +            });
这样写会导致 generateTask 为 undefined

2022-01-04 07:48 UTC, ClarkXia commented on packages/plugin-mpa/src/index.ts
> +            }
嗯 这里本质原因是 vite 和 webpack 配置的 alias 内容是不一致的，vite 下是通过 {find: string, replacement: string}[] 的方式，而 webpack 是 k-v

2022-01-04 07:49 UTC, ClarkXia commented on packages/vite-service/src/build.ts
> +  if (!configArr.length) {
目前 vite 模式下的配置均是基于 webpack 配置转化的，如果没有 webpack 配置的情况下，是不需要执行构建的，start 阶段已有这个判断，修正了下 build 模式下的逻辑

2022-01-05 08:54 UTC, SoloJiang commented on packages/plugin-mpa/src/index.ts
> +          onHook('before.build.load', async (options) => {
虽然本质上没有区别，但是 for 里面有 onHook 确实有点奇怪，onHook 'before.build.load' 里面统一去分析生成感觉好点

2022-01-05 09:40 UTC, ClarkXia commented on packages/plugin-mpa/src/index.ts
> +          onHook('before.build.load', async (options) => {
fixed

2022-01-06 03:43 UTC, SoloJiang approved these changes

2022-01-06 07:54 UTC, imsobear approved these changes

2022-01-06 07:55 UTC, merged