feat: add forceLocal of extract-css-assets plugin
alibaba/ice pull request #5378
Opened 2022-06-28 05:43 UTC by zaoy

修改了 plugin-css-assets-local 和 webpack-plugin-extract-css-assets 两个包。
加入了 forceLocal 选项，表示是否强制为本地，默认值为 false。
当 forceLocal 为 true 时，则无论 output.publicPath 是否为 http 网络路径，插件都会工作。

2022-06-28 05:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/ice?pullRequest=5378) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/ice?pullRequest=5378) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/ice?pullRequest=5378) it.</sub>

2022-06-28 05:58 UTC, ClarkXia commented
什么场景下 即便是以 publicPath 开头的绝对地址也需要重新下载？

2022-06-28 07:25 UTC, zaoy commented
> 什么场景下 即便是以 publicPath 开头的绝对地址也需要重新下载？

不是重新下载，而是把在 cdn 上的远程资源链接地址转成本地连接地址。场景是我们做本地化项目，因为不能连接外网，所有资源都需要做本地化，但是打包的脚本里包含 publicPath，所以字体资源等就无法读取本地 assets 目录里的字体文件了。这个修改的目的是即使脚本里已经定义了 publicPath，仍然将资源转成本地化。

另外说一下为什么要包含 publicPath，因为我们有日常环境和线上测试环境，日常环境可以访问线上，并且方便起见直接使用 cdn 的脚本资源来测试。同时由于有分包，所以必须打开线上发布，这样 publicPath 就一定存在。

2022-07-06 02:19 UTC, ClarkXia approved these changes

2022-07-06 06:29 UTC, luhc228 requested changes

2022-07-06 06:29 UTC, luhc228 commented on packages/webpack-plugin-extract-css-assets/README.md
> +- `forceLocal` 默认值： `falsy` 是否 publicPath 为 http 网络路径时也强制生效
默认值是 `false` 吧？

2022-07-06 07:55 UTC, zaoy commented on packages/webpack-plugin-extract-css-assets/README.md
> +- `forceLocal` 默认值： `falsy` 是否 publicPath 为 http 网络路径时也强制生效
falsy是ts的写法，已修改为false了

2022-07-21 03:45 UTC, zaoy reviewed
falsy已修改为false

2022-08-10 08:46 UTC, luhc228 approved these changes

2022-08-10 08:47 UTC, merged