增加onFirstAppear
alibaba/ice pull request #5997
Opened 2023-03-01 12:04 UTC by HomyeeKing

close #5996 
增加onFirstAppear

TODO:
- 文档

2023-03-01 12:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/ice?pullRequest=5997) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/ice?pullRequest=5997) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/ice?pullRequest=5997) it.</sub>

2023-03-01 12:15 UTC, HomyeeKing commented on packages/appear/src/visibility.ts
> -      !appearOnce(target as HTMLElement, VisibilityChangeEvent.appear)
之前加的后边这两个判断是用来干什么的
没看懂

2023-03-01 14:53 UTC, answershuto commented on packages/appear/src/index.tsx
> +  useEffect(() => listen(VisibilityChangeEvent.firstAppear, onFirstAppear), [ref, onFirstAppear, listen]);
方案上是不是直接在这一层直接加标记状态即可？

2023-03-02 02:08 UTC, ClarkXia commented on packages/appear/src/visibility.ts
> +        target.dispatchEvent(createEvent(VisibilityChangeEvent.firstAppear, {
参数上跟 appear 一致，可以优化下逻辑，统一维护

2023-03-02 02:21 UTC, answershuto commented on packages/appear/src/index.tsx
> +  useEffect(() => listen(VisibilityChangeEvent.firstAppear, onFirstAppear), [ref, onFirstAppear, listen]);
https://github.com/raxjs/rax-components/blob/8840ade56b12f4ff9cd8f26d5ef1aea37d5a7b2a/packages/rax-view/src/common/index.tsx

2023-03-02 02:25 UTC, HomyeeKing commented on packages/appear/src/visibility.ts
> +        target.dispatchEvent(createEvent(VisibilityChangeEvent.firstAppear, {
是指把`{
        direction: currentY > beforeY ? VisibilityChangeDirection.up : VisibilityChangeDirection.down,
      }` 这部分抽离出来 动态判断要dispatch的是哪个事件吗

2023-03-02 03:08 UTC, ClarkXia commented on packages/appear/src/visibility.ts
> +        target.dispatchEvent(createEvent(VisibilityChangeEvent.firstAppear, {
是的 逻辑上跟 appear 一致，可以简单增加参数判断是否为首次，大部分逻辑复用即可

2023-03-02 03:37 UTC, wssgcg1213 requested changes
如果增加了 onFirstAppear, 逻辑上可以有 onFirstClick, onFirstTouchstart, onFirstLoad, ... 这没意义

考虑下这个, 而不是去增加一个事件类型, 可以扩展到任意事件  

```jsx
function useOnce(fn) {
  const [called, setCalled] = useState(false);
  if (called) {
    return () => {};
  } else {
    return (...args) => {
      setCalled(true);
      return fn(...args);
    }; 
  }
}

export default function Index() {
  const handleAppear = () => {
    console.log('appear');
  };

  return (
    <div className={styles.app}>
      <VisibilityChange
        onAppear={useOnce(handleAppear)}
      >
          <p>
            Hello ice.js 3
          </p>
        </VisibilityChange>
    </div>
  );
}
```

2023-03-09 06:05 UTC, wssgcg1213 commented
@HomyeeKing 我们讨论了一下, 仍是觉得在 appear 里直接增加 first 处理不太妥, 所以会关闭这个 PR; 

埋点相关的需求, 我们会在内部提供一个专门用来发送埋点的组件解决     

对于通用的只执行一次回调的需求, 提供上面回复的类似 useOnce 方案来解决

2023-03-22 02:03 UTC, closed without merging