fix: fix dataLoader is sent repeatedly in PHA
alibaba/ice pull request #6062
Opened 2023-03-15 11:24 UTC by answershuto

2023-03-16 06:17 UTC, chenjun1011 commented on packages/runtime/src/dataLoader.ts
> +let dataLoaderWrapper = (dataLoader: Function, id?: number) => {
默认情况下，可以不包吗

2023-03-16 06:18 UTC, chenjun1011 commented on packages/ice/templates/core/entry.client.tsx.ejs
建议补充下 example 和 单测

2023-03-16 07:29 UTC, answershuto commented on packages/runtime/src/dataLoader.ts
> +let dataLoaderWrapper = (dataLoader: Function, id?: number) => {
那就得调用的地方判断了，跟直接返回写法上做过一个默认方法可能更合适。

2023-03-16 08:01 UTC, wssgcg1213 approved these changes

2023-03-17 02:54 UTC, wssgcg1213 commented on packages/runtime/src/dataLoader.ts
> +let dataLoaderWrapper = (dataLoader: Function, id?: number) => {
`'id' is defined but never used`

2023-03-17 02:56 UTC, wssgcg1213 commented on packages/runtime/src/dataLoader.ts
> +  wrapper: Function;
wrapper 这个概念太宽泛了, Rapper?  

抽象概念要再想一下

2023-03-17 02:56 UTC, wssgcg1213 requested changes
wrapper

2023-03-17 02:58 UTC, wssgcg1213 commented
可以参考下其它请求库是怎么封装类似的 hooks 概念的

2023-03-17 03:02 UTC, answershuto commented on packages/runtime/src/dataLoader.ts
> +let dataLoaderWrapper = (dataLoader: Function, id?: number) => {
这个是为了下方调用的地方不报 TS 类型错误，但是对于默认函数是不需要消费的，只有自定义的才会消费。

2023-05-16 06:05 UTC, wssgcg1213 commented on packages/runtime/src/dataLoader.ts
> +let dataLoaderDecorator = (dataLoader: Function, id?: number) => {
这里有 lint warning 
<img width="684" alt="image" src="https://github.com/alibaba/ice/assets/3922719/f093cc1c-b4ae-49c7-85f4-2922838a415b">

2023-05-16 09:01 UTC, wssgcg1213 approved these changes

2023-05-16 09:09 UTC, chenjun1011 approved these changes

2023-05-16 09:10 UTC, merged