fix: use data
alibaba/ice pull request #6254
Opened 2023-05-18 04:02 UTC by chenjun1011

修复 useData 无法获取数据的问题

原因是：build 时对 dataLoader 做了代码移除，而现有实现逻辑判断模块导出里 dataLoader 不存在，就直接 return 了

2023-05-18 04:51 UTC, ClarkXia commented on pnpm-lock.yaml
> +      rax-compat: 0.2.2
ci 挂了 另外 lock 生成也有问题，同步下最新的 release/next 代码

2023-05-18 07:11 UTC, answershuto commented on .changeset/sour-windows-draw.md
> +'@ice/runtime': patch
CI 报错啦

2023-05-18 07:48 UTC, ClarkXia requested changes

2023-05-18 07:48 UTC, ClarkXia commented on packages/runtime/src/routes.tsx
> +  const globalLoader = (typeof window !== 'undefined' && (window as any).__ICE_DATA_LOADER__) ? (window as any).__ICE_DATA_LOADER__ : null;
`load data from __ICE_DATA_LOADER__` 的用例挂了

2023-05-18 11:14 UTC, ClarkXia approved these changes

2023-05-19 02:48 UTC, luhc228 approved these changes

2023-05-19 03:08 UTC, merged