feat: support isPHAAppWorker
alibaba/ice pull request #6321
Opened 2023-06-13 06:26 UTC by answershuto

close https://github.com/alibaba/ice/issues/6295

2023-06-13 09:19 UTC, ClarkXia approved these changes

2023-06-13 10:04 UTC, wssgcg1213 requested changes
env.ts 里别导出了, 这里的定义跟 universal-env 里的定义是对齐的

https://unpkg.alibaba-inc.com/browse/@uni/env@1.1.1/types/index.d.ts

2023-06-13 10:05 UTC, wssgcg1213 commented
如果需要, 可以讨论一下, 并且给 @uni/env 增加一个版本

2023-06-14 02:15 UTC, answershuto commented
> 如果需要, 可以讨论一下, 并且给 @uni/env 增加一个版本

看起来这个是 universal_windvane 自己计算的，可以不导出，但是 worker 中的 target 我替换掉，原始逻辑看起来在 worker 中 isWeb 是 false 才对。

2023-06-14 03:09 UTC, ClarkXia approved these changes

2023-06-14 03:09 UTC, wssgcg1213 approved these changes

2023-06-14 03:10 UTC, merged