chore: weex support for ice appear
alibaba/ice pull request #6391
Opened 2023-07-17 01:44 UTC by linbudu599

2023-07-17 05:50 UTC, answershuto commented
pr 描述需要补全

2023-07-17 05:50 UTC, answershuto commented on packages/appear/src/weex/index.tsx
> +  }, []);
wanring

2023-07-17 05:51 UTC, answershuto commented on packages/appear/src/weex/index.tsx
> +        childrenRef.current?.removeEventListener('disappear', (e: CustomEvent) => onDisappear(e));
warning

2023-07-18 02:38 UTC, luhc228 commented on packages/appear/src/typings.ts
> +   * 元素离开可视区域触发的事件
注释可考虑跟原来统一用英文

2023-07-18 09:17 UTC, wssgcg1213 requested changes
同上

2023-07-26 06:45 UTC, wssgcg1213 approved these changes

2023-07-26 08:32 UTC, luhc228 approved these changes

2023-08-01 05:29 UTC, merged

2023-11-27 08:15 UTC, myhere commented on packages/appear/src/weex/index.tsx
> +      onAppear && nodeRef?.removeEventListener('appear', (e: CustomEvent) => onAppear(e));
hi，@linbudu599 weex 下 addEventListener、removeEventListener 对 onAppear 都加了一层 wrapper，所以这里 removeEventListener 是不是就不生效了