RaxCompatPlugin 0.3.0
alibaba/ice pull request #6718
Opened 2023-12-27 06:39 UTC by linbudu599

重构了插件的功能实现，修正了目前的已知问题：

- inlineStyle 在 SSR（原 `applyStylesheetLoaderForServer` 方法） 下完全没有生效
- SSR 下 `esbuild-plugin-inline-style` 无法处理 less 文件中的相对引用支持（`@import './variables.less'`）
- inlineStyle 对 `less`、`scss` 文件目前不生效
- `.scss` / `.sass` 样式支持

2023-12-27 07:16 UTC, answershuto commented on packages/plugin-rax-compat/src/index.ts
> +import type { Plugin } from '@ice/app/types';
`@ice/app/types` type import should occur before import of `./services/alias`

2023-12-27 07:20 UTC, wssgcg1213 commented on packages/plugin-rax-compat/README.md
> +### `cssModule`
CSS Modules ?

2024-01-02 02:33 UTC, wssgcg1213 commented on packages/plugin-rax-compat/README.md
> +- Enable legacy syntax to import Rax like this:
这里的描述应该是: 兼容到 rax.js v0.6 版本
因为默认是兼容到 rax.js v1.x 版本的

2024-01-02 02:33 UTC, wssgcg1213 commented on packages/plugin-rax-compat/README.md
> +- Enable legacy syntax to import Rax like this:
这两个版本的导出和表现有一些细微差异

2024-01-02 02:35 UTC, wssgcg1213 requested changes
整体逻辑没有问题, Action check 和单元测试需要再检查一下

2024-01-02 03:47 UTC, linbudu599 commented on packages/plugin-rax-compat/README.md
> +### `cssModule`
这里是 compat 插件内部的 cssModule 配置

2024-01-02 07:18 UTC, closed without merging